An assignment for my CST4802 Information Retrieval course at CityTech.

Implementing kNN algorithm (using only Numpy)

In [ ]:
# creating the training data

sepal_lengths = [5.3, 5.1, 7.2, 5.4, 5.1, 5.4, 7.4, 6.1, 7.3, 6.0, 5.8, 6.3, 5.1, 6.3, 5.5]
sepal_widths =  [3.7, 3.8, 3.0, 3.4, 3.3, 3.9, 2.8, 2.8, 2.9, 2.7, 2.8, 2.3, 2.5, 2.5, 2.4]
species = ['Setosa', 'Setosa', 'Virginica', 'Setosa', 'Setosa', 'Setosa', 'Virginica', 'Verscicolor', 'Virginica', 'Verscicolor', 'Virginica', 'Verscicolor', 'Verscicolor', 'Verscicolor', 'Verscicolor',]

import pandas as pd # using pandas to view the training data

df = pd.DataFrame({'Sepal Length':sepal_lengths, 'Sepal Width':sepal_widths, 'Species':species})
df

Sepal Length  Sepal Width      Species
0            5.3          3.7       Setosa
1            5.1          3.8       Setosa
2            7.2          3.0    Virginica
3            5.4          3.4       Setosa
4            5.1          3.3       Setosa
5            5.4          3.9       Setosa
6            7.4          2.8    Virginica
7            6.1          2.8  Verscicolor
8            7.3          2.9    Virginica
9            6.0          2.7  Verscicolor
10           5.8          2.8    Virginica
11           6.3          2.3  Verscicolor
12           5.1          2.5  Verscicolor
13           6.3          2.5  Verscicolor
14           5.5          2.4  Verscicolor

In [ ]:
# Seperating the data into features and labels
X = df.drop("Species", axis=1) # all features except "Species"
X = X.values
y = df["Species"] # only "Species"
y = y.values

In [ ]:
# creating the test data
import numpy as np

test_entry = np.array([5.2, 3.1])
test_entry

array([5.2, 3.1])

In [ ]:
# computing the distances between the test_entry and each of the data points in the dataset
distances = np.linalg.norm(X - test_entry, axis=1) # computing the norm of the distance between vectors
distances

array([0.60827625, 0.70710678, 2.00249844, 0.36055513, 0.2236068 ,
       0.82462113, 2.22036033, 0.9486833 , 2.10950231, 0.89442719,
       0.67082039, 1.36014705, 0.60827625, 1.25299641, 0.76157731])

In [ ]:
# finding out the closest k neighbors
k = 3 # picking a k value
nearest_neighbor_indices = distances.argsort()[:k] # sorting the distances and taking the top k shortest distances
nearest_neighbor_indices

array([4, 3, 0])

In [ ]:
# matching the indices to the classes/labels
nearest_neighbors_labels = y[nearest_neighbor_indices]
nearest_neighbors_labels

array(['Setosa', 'Setosa', 'Setosa'], dtype=object)

In [ ]:
# using the mode to predict the class/label of the test_entry
from statistics import mode

prediction = mode(nearest_neighbors_labels)
prediction

'Setosa'